# Generated by Django 4.2.8 on 2024-07-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('myapp', '0004_customadmin_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomAdmin',
            new_name='CustomUser',
        ),
    ]
