# Generated by Django 4.2.8 on 2024-07-26 10:50

from django.db import migrations, models
import myapp.managers


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_customadmin_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', myapp.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
